### ISSUE TITLE
Combine coverage between jobs

### ISSUE THREAD

**Issue by lafrech** [asottile/azure-pipeline-templates#36]
Hi.

I'm trying to move flask-smorest CI from Travis to Azure (https://github.com/marshmallow-code/flask-smorest/pull/195) using azure-pipeline-templates (@sloria's fork, actually, to get the PyPI release template). Thanks for sharing those templates.

My concern is the coverage report.

AFAIU, when using the coverage feature of `job--python-tox`, the coverage that is displayed is the one of the job that finishes last. This is fine if all jobs have the same coverage, but wrong if jobs don't pass through all branches (e.g. testing conditional code against different versions of a dependency, or different Python versions).

I've been searching the web for solutions to this. Apparently Azure doesn't do a great job with this. Some suggest to use a third-party app called ReportGenerator.

I have the feeling it should be possible to keep the coverage report for each job using [pipeline artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts), then combining them in a later stage using `coverage combine`.

A CI pipeline could look like

```
- lint
  flake8
- tests
  pytest py36-dep-v1 + publish coverage as pipeline artifact
  pytest py36-dep-v2 + publish coverage as pipeline artifact
  pytest py39-dep-v1 + publish coverage as pipeline artifact
  pytest py39-dep-v2 + publish coverage as pipeline artifact
- coverage
  download coverage infos as pipeline artifacts + combine + check threshold (`fail-under`) + publish code coverage result
- release
  send to pypi
```  

Is my understanding correct about current issue?

Is this something you would like to address? Does the proposal above make sense?

I've spent hours struggling with Azure and I feel like I'm still scratching the surface.

**Comment by asottile** [comment]
hmmm I could have sworn AP used to combine the different coverage reports themselves, I'm not sure what's changed there

but yeah mostly sounds fine -- I probably wouldn't use the combine feature myself so if you can make it optional that would be best (all of my coverage reports are the same)

**Comment by lafrech** [comment]
My coverage reports are the same right now but it might change in the future as testing against different dep versions is a frequent use case. And I have a 100% coverage on flask-smorest I'd like to keep.

Can't promise I'll be looking into it soon. I've spent way too much time on this already. But thanks for validating the principle.
