### ISSUE TITLE
Cannot build forks

### ISSUE THREAD

**Issue by hugovk** [asottile/azure-pipeline-templates#9]
Out of curiosity, I tried building my fork of pyupgrade on my own Azure Pipelines account but it didn't work:
 
> Repository asottile references endpoint asottile-github which does not exist or is not authorized for use

![image](https://user-images.githubusercontent.com/1324225/53972757-1175fe00-4108-11e9-9e97-da9b2aeb5f84.png)

https://dev.azure.com/hugovk/hugovk/_build/results?buildId=126&view=results

Probably not surprising, as you've documented that the user needs to find the name of their GitHub service connection.

https://github.com/asottile/azure-pipeline-templates#usage

(I couldn't actually find "Project Settings => Service connections in the Azure Devops dashboard for your project", but that's not the main point of this particular issue.)

So it looks like I'd have to put my own value in my forked `azure-pipelines.yml`, but that would be a pain when wanting to make a PR back upstream.

This is definitely a downside when comparing against Travis which is easy to enable and use for a fork (eg. `travis sync && travis enable` CLI, or click a couple of button in the UI).

I wonder if there's anything to be done about this? Perhaps the endpoint could be included from another YAML file that's Git ignored? Is it something that should be reported to Azure Pipelines?

This is not urgent in any way! Just thought you might be interested to hear :)

**Comment by asottile** [comment]
I guess the directions could be changed to "make an endpoint called asottile-github" :man_shrugging: 

Does that work?

**Comment by hugovk** [comment]
I'll give it a try. Where exactly do I find that in Azure?

**Comment by asottile** [comment]
From the root of your account (in my case I only have one "Project" in my "Organization" -- they happen to have the same name, the left column is organizations, the right  column is projects).  I clicked on my one project:

![screenshot from 2019-03-07 09-42-08](https://user-images.githubusercontent.com/1810591/53977236-75270980-40bd-11e9-807b-0d0d7ad3a843.png)

Then it took me to this page:

![screenshot from 2019-03-07 09-43-04](https://user-images.githubusercontent.com/1810591/53977308-9687f580-40bd-11e9-820a-0b888465b6fd.png)

From there, click on "Project Settings" in the very bottom left, from there it should be straightforward

**Comment by hugovk** [comment]
Thanks, it worked!

![image](https://user-images.githubusercontent.com/1324225/53985184-a803e880-4123-11e9-8979-647a88e52432.png)


https://dev.azure.com/hugovk/hugovk/_build/results?buildId=164

(Side notes: https://hugovk.visualstudio.com redirected me to https://dev.azure.com/hugovk/ (it's a new account) and I had the sidebar minimised showing just the cogwheel.)

**Comment by asottile** [comment]
makes sense, my account is old from back when I used it for visual studio hosted.

Perhaps I should change my connection to a more generic "github" name to make it easier for everyone?

**Comment by hugovk** [comment]
Yes, something generic like that sounds good.

**Comment by asottile** [comment]
Making sure this works and then I'll adjust all of mine and probably the directions here as well: https://github.com/asottile/pyupgrade/pull/109/files

**Comment by hugovk** [comment]
https://dev.azure.com/hugovk/hugovk/_build/results?buildId=165

Confirmed still working after rename. Thanks!

**Comment by asottile** [comment]
awesome!
